### ISSUE TITLE
0.4.0 installation crash

### ISSUE THREAD

**Issue by IliasDeros** [btecu/ember-cli-bootstrap-datetimepicker#30]
Attempting to install latest (0.4.0) `ember-cli-bootstrap-datetimepicker` results in the following error :
`Unexpected token {`

```
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Class.CoreObject.extend.config (/home/ilias/Documents/Dev/triage-frontend/node_modules/ember-cli/lib/models/addon.js:898:29)
    at /home/ilias/Documents/Dev/triage-frontend/node_modules/ember-cli/lib/models/project.js:224:29
    at Array.reduce (native)
```

**Workaround**: Use the following install command instead :
```
ember install ember-cli-bootstrap-datetimepicker@0.3.1
```

Versions information :
**ember-cli**: 2.10.0
**Node** 4.6.2

**Comment by btecu** [comment]
Can you update your `node` to version `6` or `7` try again?

I can't reproduce this issue.
