### ISSUE TITLE
Releases 0.4.0 and 0.4.1 cannot be installed

### ISSUE THREAD

**Issue by bugduino** [btecu/ember-cli-bootstrap-datetimepicker#32]
trying to `ember install ember-cli-bootstrap-datetimepicker@0.4.1` or 0.4.0
gives the following error

```
Unexpected token {
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at CoreObject.extend.config (/home/foo/Projects/bar/pt-abp/node_modules/ember-cli/lib/models/addon.js:810:29)
    at /home/foo/Projects/bar/pt-abp/node_modules/ember-cli/lib/models/project.js:223:27
    at Array.reduce (native)
```

**Comment by DavorPadovan** [comment]
Which Node version are you using? I had similar problem - Node upgrade solved it.

**Comment by bugduino** [comment]
v5.3.0

**Comment by bugduino** [comment]
The affected commit should be the following one https://github.com/btecu/ember-cli-bootstrap-datetimepicker/commit/a9c8b4d3aaca9026d3ff9260dd219623b6409c89

**Comment by DavorPadovan** [comment]
I'm using v7.4.0 and it works for me.

**Comment by bugduino** [comment]
Ok thank you

Il lun 23 gen 2017, 11:07 Davor Padovan <notifications@github.com> ha
scritto:

**Comment by btecu** [comment]
Yes, the requirements list `Node.js 6 or newer`.
