### ISSUE TITLE
Use of const in strict mode

### ISSUE THREAD

**Issue by ngelx** [btecu/ember-cli-bootstrap-datetimepicker#7]
Hi, I'm trying to install this addon but I'm getting the next issue.

```
vagrant@packer-debian-7:~/$` ember install ember-cli-bootstrap-datetimepicker
Installed packages for tooling via npm.
./node_modules/ember-cli-bootstrap-datetimepicker/index.js:4
const Funnel = require('broccoli-funnel');
^^^^^
Use of const in strict mode.
./node_modules/ember-cli-bootstrap-datetimepicker/index.js:4
const Funnel = require('broccoli-funnel');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Function.Addon.lookup (./node_modules/ember-cli/lib/models/addon.js:879:19)
    at ./node_modules/ember-cli/lib/models/addons-factory.js:47:36
    at visit (./node_modules/ember-cli/lib/utilities/DAG.js:23:3)
```

Thanks,

**Comment by btecu** [comment]
What version of `ember-cli` are you using?
Do you have `babeljs` in your project.

**Comment by ngelx** [comment]
Sorry!

```
vagrant@packer-debian-7:~/$ ember -v
ember-cli: 2.4.3
node: 0.12.7
os: linux x64
```
thanks

**Comment by btecu** [comment]
In your `package.json`, do you have `"ember-cli-babel": "^5.1.6"` or a similar version?

**Comment by ngelx** [comment]
Exactly that
```
    ...
    "ember-cli-babel": "^5.1.6",
    ...
```

**Comment by btecu** [comment]
I'm not able to reproduce. I have the same version of `ember-cli` as you do but a newer `node` version (5.9.1).

**Comment by btecu** [comment]
Could you update `node` to version 5 and see if that's the problem?

**Comment by ngelx** [comment]
Hey @btecu give me a few days please. I'm in a middle of a project and don't want break anything. I'll come back to you later when its done.

Thanks,

**Comment by ngelx** [comment]
I've updated to node: 5.10.0 and the issue is gone. 
Thanks
